version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      #Corretto-17.0.6.10.1
  #pre_build:
  #  commands:
  #    - echo Nothing to do in the pre_build phase...
  #    - yum install java-17-amazon-corretto-devel -y
  #    - alternatives --set java /usr/lib/jvm/java-17-amazon-corretto.aarch64/bin/java
  build:
    commands:
      - ./gradlew bootJar
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - build/libs/*.jar
    - scripts/*.sh
    - appspec.yml
  # com/mycompany/app/HelloWorld.java, specifying yes will place this file in /HelloWorld.java
  discard-paths: yes